// public sidebarItems = [
//     {
//       title: 'Media',
//       icon: '&#9660;',
//       isOpenKey: 'media',
//       subItems: [
//         { title: 'Media Manager', route: this.routes.media_manager },
//         { title: 'Create Media', route: this.routes.media_manager_create },
//         { title: 'Media Manager Settings', route: this.routes.media_manager_settings }
//       ]
//     },
//     {
//       title: 'Users',
//       icon: '&#9660;',
//       isOpenKey: 'users',
//       subItems: [
//         { title: 'Instructors', route: this.routes.users_instructors},
//         { title: 'Insturctors Payout', route: this.routes.users_instructors_payout },
//         { title: 'Students', route: this.routes.users_students },
//         { title: 'Staffs', route: this.routes.users_staffs},
//         { title: 'Roles', route: this.routes.users_roles },

//         { title: 'Delete Account Requests', route: this.routes.users_delete_account_requests }

//       ]
//     },
//     {
//       title: 'Settings',
//       icon: '&#9660;',
//       isOpenKey: 'settings',
//       subItems: [
//         { title: 'System Settings', route: this.routes.settings_system },
//         { title: 'API Settings', route: this.routes.settings_api },
//         { title: 'SMS Settings', route: this.routes.settings_sms },
//         { title: 'Vimeo Settings', route: this.routes.settings_vimeo },
//         { title: 'Vdocipher Settings', route: this.routes.settings_vdocipher },
//         { title: 'Localization Settings', route: this.routes.settings_localization },
//         { title: 'Module Manager', route: this.routes.settings_module_manager },
//         { title: 'Sidebar Manager', route: this.routes.settings_sidebar_manager },
//         { title: 'Themes Settings', route: this.routes.settings_themes },
//         { title: 'Themes Customize', route: this.routes.settings_themes_customize },
//         { title: 'Themes Font', route: this.routes.settings_themes_font },
//         { title: 'Newsletter Settings', route: this.routes.settings_newsletter },
//         { title: 'Mailchimp Settings', route: this.routes.settings_newsletter_mailchimp },
//         { title: 'GetResponse Settings', route: this.routes.settings_newsletter_get_response },
//         { title: 'Acelle Settings', route: this.routes.settings_newsletter_acelle },
//         { title: 'Subscriber Settings', route: this.routes.settings_newsletter_subscriber },
//         { title: 'Push Notification Settings', route: this.routes.settings_push_notification },
//         { title: 'Utilities Settings', route: this.routes.settings_utilities },
//         { title: 'Preloader Settings', route: this.routes.settings_preloader },
//         { title: 'Geo Location Settings', route: this.routes.settings_geo_location },
//         { title: 'Error Log Settings', route: this.routes.settings_error_log },
//         { title: 'IP Block Settings', route: this.routes.settings_ip_block },
//         { title: 'Maintenance Settings', route: this.routes.settings_maintenance },
//         { title: 'Update System Settings', route: this.routes.settings_update_system },
//         { title: 'City Settings', route: this.routes.settings_city },
//         { title: 'Cache Settings', route: this.routes.settings_cache },
//         { title: 'Queue Settings', route: this.routes.settings_queue },
//         { title: 'Cron Job Settings', route: this.routes.settings_cron_job },
//         { title: 'Captcha Settings', route: this.routes.settings_captcha },
//         { title: 'Social Login Settings', route: this.routes.settings_social_login },
//         { title: 'Payout Accounts Settings', route: this.routes.settings_payout_accounts },
//         { title: 'Cookie Settings', route: this.routes.settings_cookie },
//         { title: 'Analytics Settings', route: this.routes.settings_analytics },
//         { title: 'Pusher Settings', route: this.routes.settings_pusher },
//         { title: 'Gdrive Settings', route: this.routes.settings_gdrive },
//         { title: 'SEO Settings', route: this.routes.settings_seo },
//         { title: 'Currencies Settings', route: this.routes.settings_currencies },
//         { title: 'Timezone Settings', route: this.routes.settings_timezone },
//         { title: 'Activation Settings', route: this.routes.settings_activation },
//         { title: 'General Settings', route: this.routes.settings_general },
//         { title: 'Email Settings', route: this.routes.settings_email },
//         { title: 'Email Template Settings', route: this.routes.settings_email_template },
//         { title: 'Payout Settings', route: this.routes.settings_payout },
//         { title: 'Backup Settings', route: this.routes.settings_backup }
//       ]
//     },
//     {
//       title: 'No Main Route',
//       icon: '&#9660;',
//       isOpenKey: 'noMainRoute',
//       subItems: [
//         { title: 'Departments', route: this.routes.departments },
//         { title: 'Course Categories', route: this.routes.courses_categories },
//         { title: 'Course Levels', route: this.routes.courses_levels },
//         { title: 'Course Settings', route: this.routes.courses_settings },
//         { title: 'Course Subjects', route: this.routes.courses_subjects },
//         { title: 'Question Groups', route: this.routes.quizzes_question_groups },
//         { title: 'Question Banks', route: this.routes.quizzes_question_banks },
//         { title: 'Quiz Setups', route: this.routes.quizzes_setups },
//         { title: 'Quiz Results', route: this.routes.quizzes_results },
//         { title: 'Virtual Classes', route: this.routes.virtual_classes },
//         { title: 'Zoom Settings', route: this.routes.zoom_settings },
//         { title: 'Certificates', route: this.routes.certificates },
//         { title: 'Certificate Fonts', route: this.routes.certificates_fonts },
//         { title: 'Certificate Settings', route: this.routes.certificates_settings },
//         { title: 'Revenue', route: this.routes.revenue },
//         { title: 'Instructors Revenue', route: this.routes.revenue_instructors },
//         { title: 'Revenue Statistics', route: this.routes.revenue_statistics },
//         { title: 'Enrollments', route: this.routes.enrollments },
//         { title: 'Refund and Cancellation', route: this.routes.enrollments_refund_n_cancellation },
//         { title: 'Refund Settings', route: this.routes.enrollments_refund_settings },
//         { title: 'Notifications', route: this.routes.communication_notifications },
//         { title: 'Private Messages', route: this.routes.communication_private_messages },
//         { title: 'Manage Coupons', route: this.routes.coupons_manage },
//         { title: 'Single Coupons', route: this.routes.coupons_single },
//         { title: 'Personalized Coupons', route: this.routes.coupons_personalized },
//         { title: 'Invite Code Coupons', route: this.routes.coupons_invite_code },
//         { title: 'Invite Settings', route: this.routes.coupons_invite_settings },
//         { title: 'Online Payment', route: this.routes.payment_online },
//         { title: 'Offline Payment', route: this.routes.payment_offline },
//         { title: 'Bank Payment', route: this.routes.payment_bank },
//         { title: 'Payment Commission', route: this.routes.payment_commission },
//         { title: 'Blogs', route: this.routes.blogs },
//         { title: 'Blog Comments', route: this.routes.blogs_comments },
//         { title: 'Questions', route: this.routes.questions },
//         { title: 'Question Settings', route: this.routes.questions_settings },
//         { title: 'Header Menu', route: this.routes.cmo_header_menu },
//         { title: 'Menu Settings', route: this.routes.cmo_menu_settings },
//         { title: 'Sliders', route: this.routes.cmo_sliders },
//         { title: 'Slider Settings', route: this.routes.cmo_sliders_settings },
//         { title: 'Page Content', route: this.routes.cmo_page_content },
//         { title: 'Testimonials', route: this.routes.cmo_testimonials },
//         { title: 'Social Settings', route: this.routes.cmo_social_settings },
//         { title: 'Pages', route: this.routes.cmo_pages },
//         { title: 'Become an Instructor', route: this.routes.cmo_become_instructor },
//         { title: 'Sponsors', route: this.routes.cmo_sponsors },
//         { title: 'Popup Content', route: this.routes.cmo_popup_content },
//         { title: 'Footer Settings', route: this.routes.cmo_footer_settings },
//         { title: 'Login Page', route: this.routes.cmo_login_page },
//         { title: 'FAQ', route: this.routes.cmo_faq },
//         { title: 'Header Footer Style', route: this.routes.cmo_header_footer_style },
//         { title: 'Gamification', route: this.routes.gamification },
//         { title: 'Gamification Badges', route: this.routes.gamification_badges },
//         { title: 'Gamification History', route: this.routes.gamification_history }
//       ]
//     },
    
//   ];